import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/src/component/Navbar";
import "./globals.css";

//import { ThemeProvider } from "@/src/context/ThemeContext";
import StoreInitializer from "@/src/component/StoreInitializer";
//import { LikesProvider } from "@/src/context/LikesContext";
/* import Navbar from "@/src/component/Navbar";
 */
import CartDrawer from "@/src/component/CartDrawer";
import AmbientBackground from "@/src/component/AmbientBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeScript = `
  (function() {
    try {
      const storedTheme = localStorage.getItem('app_theme');
      if (storedTheme === 'dark') {
        document.documentElement.classList.add('dark');
      } else {
        document.documentElement.classList.remove('dark');
        }
    } catch (e) {}
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //因為layout 是父層，資料 Props 只能向下走不能往回逆流，所以父層無從得知page.tsx的按讚數量!
  /* const totalLikes = 0; */

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900 dark:bg-gray-950 dark:text-gray-100 `}>
        <script 
          dangerouslySetInnerHTML={{ __html: themeScript }}/>
            <AmbientBackground />
            <StoreInitializer /> {/* 初始化元件 */}   
            <Navbar /* totalLikes={totalLikes} *//>
            <CartDrawer />
            {children} {/* Component Composition (元件組合)的關鍵 */}         
      </body>
    </html>
  );
}
